# Generated by Django 5.2 on 2025-05-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerid', models.AutoField(primary_key=True, serialize=False)),
                ('offer_price', models.IntegerField()),
                ('offer_date', models.DateField()),
                ('offer_expiry_date', models.DateField()),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
