# Generated by Django 5.2.1 on 2025-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_price', models.IntegerField()),
                ('offer_date', models.DateField()),
                ('offer_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contingent', 'Contingent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
