# Generated by Django 5.2.1 on 2025-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_price', models.IntegerField()),
                ('offer_date', models.DateField()),
                ('offer_expiry_date', models.DateField()),
            ],
        ),
    ]
