# Generated by Django 5.2.1 on 2025-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (104, '104'), (105, '105'), (106, '106'), (107, '107'), (108, '108'), (109, '109'), (110, '110'), (111, '111'), (112, '112'), (113, '113'), (116, '116'), (161, '161'), (162, '162'), (170, '170'), (200, '200'), (201, '201'), (202, '202'), (203, '203'), (206, '206'), (210, '210'), (212, '212'), (225, '225'), (220, '220'), (221, '221'), (222, '222'), (230, '230'), (232, '232'), (240, '240'), (241, '241'), (270, '270'), (271, '271'), (276, '276'), (300, '300'), (400, '400'), (401, '401'), (550, '550'), (600, '600'), (601, '601'), (602, '602'), (700, '700'), (735, '735'), (736, '736'), (800, '800'), (801, '801'), (870, '870'), (871, '871'), (900, '900'), (901, '901')])),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Bungalow', 'Bungalow'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse')], max_length=50)),
                ('price', models.IntegerField()),
                ('build_date', models.DateField()),
                ('description', models.CharField(max_length=4096)),
                ('bathroom', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('property_status', models.BooleanField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
