# Generated by Django 5.2.1 on 2025-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('location', models.CharField(choices=[('101 - Reykjavík', '101 - Reykjavík'), ('102 - Reykjavík', '102 - Reykjavík'), ('103 - Reykjavík', '103 - Reykjavík'), ('104 - Reykjavík', '104 - Reykjavík'), ('105 - Reykjavík', '105 - Reykjavík'), ('106 - Reykjavík', '106 - Reykjavík'), ('107 - Reykjavík', '107 - Reykjavík'), ('108 - Reykjavík', '108 - Reykjavík'), ('109 - Reykjavík', '109 - Reykjavík'), ('110 - Reykjavík', '110 - Reykjavík'), ('111 - Reykjavík', '111 - Reykjavík'), ('112 - Reykjavík', '112 - Reykjavík'), ('113 - Reykjavík', '113 - Reykjavík'), ('116 - Reykjavík', '116 - Reykjavík'), ('161 - Reykjavík', '161 - Reykjavík'), ('162 - Reykjavík', '162 - Reykjavík'), ('170 - Seltjarnarnes', '170 - Seltjarnarnes'), ('200 - Kópavogur', '200 - Kópavogur'), ('201 - Kópavogur', '201 - Kópavogur'), ('202 - Kópavogur', '202 - Kópavogur'), ('203 - Kópavogur', '203 - Kópavogur'), ('206 - Kópavogur', '206 - Kópavogur'), ('210 - Garðabær', '210 - Garðabær'), ('212 - Garðabær', '212 - Garðabær'), ('225 - Garðabær', '225 - Garðabær'), ('220 - Hafnafjörður', '220 - Hafnafjörður'), ('221 - Hafnafjörður', '221 - Hafnafjörður'), ('222 - Hafnafjörður', '222 - Hafnafjörður'), ('230 - Keflavík', '230 - Keflavík'), ('232 - Keflavík', '232 - Keflavík'), ('240 - Grindavík', '240 - Grindavík'), ('241 - Grindavík', '241 - Grindavík'), ('270 - Mosfellsbær', '270 - Mosfellsbær'), ('271 - Mosfellsbær', '271 - Mosfellsbær'), ('276 - Mosfellsbær', '276 - Mosfellsbær'), ('300 - Akranes', '300 - Akranes'), ('400 - Ísafjörður', '400 - Ísafjörður'), ('401 - Ísafjörður', '401 - Ísafjörður'), ('550 - Sauðárkrókur', '550 - Sauðárkrókur'), ('600 - Akureyri', '600 - Akureyri'), ('601 - Akureyri', '601 - Akureyri'), ('602 - Akureyri', '602 - Akureyri'), ('700 - Egilsstaðir', '700 - Egilsstaðir'), ('735 - Eskifjörður', '735 - Eskifjörður'), ('736 - Eskifjörður', '736 - Eskifjörður'), ('800 - Selfoss', '800 - Selfoss'), ('801 - Selfoss', '801 - Selfoss'), ('870 - Vík', '870 - Vík'), ('871 - Vík', '871 - Vík'), ('900 - Vestmannaeyjar', '900 - Vestmannaeyjar'), ('901 - Vestmannaeyjar', '901 - Vestmannaeyjar')], max_length=100)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Bungalow', 'Bungalow'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse')], max_length=50)),
                ('price', models.IntegerField()),
                ('build_date', models.DateField()),
                ('description', models.CharField(max_length=4096)),
                ('bathroom', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('property_status', models.BooleanField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
