# Generated by Django 5.2.1 on 2025-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.IntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('build_date', models.DateField()),
                ('description', models.CharField(max_length=4096)),
                ('bathroom', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('property_status', models.BooleanField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
